- hosts: '{{ hosts }}'
  remote_user: root
  become: yes
  gather_facts: True
  tasks:
    - name: backup | 创建存储备份的文件夹
      file: path={{ tomcat_path }}backup state=directory

    - name: backup | cp war
      shell: cp -r {{ tomcat_path }}webapps/demo.war  {{ tomcat_path }}backup/demo-`date '+%F'`.war
      ignore_errors: true

    - name: stop |  停止tomcat
      shell: "{{ tomcat_path }}bin/catalina.sh stop -force"

    - name: stop |  等待端口关闭
      wait_for: port={{ tomcat_port }} state=stopped delay=3

    - name: check | 检查 catalina.sh 是否关闭成功
      shell: ps -ef | grep tomcat | grep {{ tomcat_path }} | grep -v grep | awk '{print $2}'
      register: var_pid

    - name: debug | 打印 pid
      debug: msg="{{ var_pid }}"

    - name: stop |  强制 停止tomcat
      shell: kill -9 {{ var_pid.stdout }}
      when: var_pid.stdout != ''

    - name: stop |  清理旧文件
      shell: "rm -rf {{ tomcat_path }}{{ item }}/*"
      with_items:
        - webapps
        - work
        - logs
        - temp

    - name: deploy | 上传war
      copy: src={{ workspace }}/target/demo.war dest={{ tomcat_path }}webapps/demo.war

    - name: deploy | 启动服务
      shell: chdir={{ tomcat_path }}bin nohup ./catalina.sh start &
      ignore_errors: true